### ISSUE TITLE
but is an incompatible architecture (have (x86_64), need (arm64e)))

### ISSUE THREAD

**Issue by mfch101** [tuxu/python-samplerate#11]
I running the code on mac M1, and meet the problem below for a whole day. 

/lib/python3.11/site-packages/samplerate/_samplerate_data/libsamplerate.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

**Comment by fakufaku** [comment]
Hi @mfch101 , we are currently preparing a new version that should also compile on mac M1.

If you want to test it, you could try to install directly from the new branch [pybind11-refactor](https://github.com/tuxu/python-samplerate/tree/pybind11-refactor)
```bash
pip install -e git+https://github.com/tuxu/python-samplerate.git@pybind11-refactor
```

**Comment by matangover** [comment]
@fakufaku Thanks for this! For me the command you gave didn't work, I had to add the egg name like this:

```
pip install -e git+https://github.com/tuxu/python-samplerate.git@pybind11-refactor#egg=samplerate
```

**Comment by ideoforms** [comment]
@fakufaku Just to let you know that I have also just verified that the `pybind11-refactor` branch also works for me on an M1 MacBookPro (verified with both x86_64 and arm64 versions of Python 3.12). Looking forward to the new build being on PyPi, I use the library a lot. Thanks for all the work on it!
