### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [tuxu/python-samplerate#18]
Could you please tag the source again? Otherwise all distributions which were shipping this Python module and were using the GitHub releases need to change their description to build the packages.

Thanks

**Comment by fakufaku** [comment]
Hi @fabaff , do you mean create a release from the tag used for the pypi release? In that case, I think it should be possible.

**Comment by fabaff** [comment]
Hmm, now I see 0.2.1 at https://github.com/tuxu/python-samplerate/tags. I really hope that I didn't bother you for nothing.

**Comment by fakufaku** [comment]
The tags are there, but no release page was created. Do you need the release page with the description?
